dist: xenial

sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull
  - sudo apt-get update
  - sudo apt install moreutils

before_script:
  - cd src/ontology

script:
  - ./run.sh make test  | ts -s %M:%S

# whitelist
branches:
  only:
    - master
    - test-travis

### UNCOMMENT THIS AND ADD YOUR DETAILS:
#notifications:
#  email:
#    - YOURNAME@YOU.ORG
